"""add is_active to farm

Revision ID: 684d0875c4c8
Revises: e359593f5d31
Create Date: 2025-01-19 21:41:04.327528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684d0875c4c8'
down_revision = 'e359593f5d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
