name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: 161.35.70.99
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/supplo.ai
            git pull origin main
            
            # Vytvoření potřebných adresářů
            mkdir -p app/static/uploads
            mkdir -p app/data
            chmod -R 755 app/static/uploads
            chmod -R 755 app/data
            
            # Nastavení prostředí
            source venv/bin/activate
            pip install -r requirements.txt
            export FLASK_ENV=production
            export PORT=80
            
            # Restart služby
            systemctl restart supplo 